services:
# nginx
  web:
    build:
        dockerfile: ./nginx/Dockerfile
        context: .
    ports:
            - "80:80"    
    volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./Dockerfile    
      context: .
    volumes:
      - ./app:/app      
# php