services:
# nginx
  web:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./Dockerfile    
      context: .
    ports:
      - 9004:9004  
# php